### ISSUE TITLE
Checkpoint 1 is ready

### ISSUE THREAD

**Issue by eburzlaff** [eburzlaff/RealEstateApp#1]
@pawaitemadisoncollege

**Comment by pawaitemadisoncollege** [comment]
Hi @eburzlaff!

**Problem statement**

- [ ] I'm curious how your solution will be different from some sites like Zillow, MLS, FSBO, etc.

**user stories w/ MVP identified**

- [ ] One of the ent java requirements for the indie project is  CRUD (create-read-update-delete). I think the only one not currently covered is delete. Is there a meaningful story that you can add to meet this requirement?
- [ ] Are all stores MVP? I would suggest identifying the MVP as the stories needed  hit the Ent Java requirements, plus any others that you feel strongly that you want to implement for version 1. 

This story might be better called search property. It could also be two stories - search by location and search by cost.
> View Property
> 
> As any user, I want to be able to search for properties by location or cost so that I could choose the best option.


**project plan**

- [ ] Missing most details. One way to gain some traction here might be to consider each user story and plan when you will work on each one. Then add details for what tasks you think you may need to complete in order to accomplish the story. 

**screen design**

- [ ] I am not sure all user stories are represented. How will a user edit a property?
- [ ] Should the search screen have a way to choose search criteria?

**timelog/reflection statements** 

- [ ] Looks like journal may be a bit out of date. You do not have to use both the time log and the journal unless you find tracking in both useful (I prefer to do it this way, but I won't want you to do if you do not find it valuable).

**other**

- [ ] Have you thought about a web service or api to use in your project yet?  A couple ideas include: Amazon S3 to host  images of the properties,  Javamail to be able to contact the property seller, an api to validate the address/zip, or an api to search for properties within a certain radius. 

Looking forward to seeing checkpoint 2 soon (remember it was due on Wednesday, Oct 12)!
